# Site settings
title: An anthropology of new technologies
email: pm@lvq.me
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pmleveque.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  pmleveque

# Build settings
markdown: kramdown
